### PR TITLE
Got GCE deployment working with mesos configuration to allow dispatch…

### PR DESCRIPTION
**Pull request by clalansingh**
…ing jobs from mesos-master to the workers

### CODE REVIEW

**Comment by kellrott** [comment]
Is it worth pushing ansible-docker.patch and ansible-mesos.patch back to the original projects as pull requests?

**Comment by clalansingh** [comment]
The mesos change is just one line in a config file, so not something to push out, but the docker patch might be. The GCE nodes weren't able to find the linux-image-extra package for their kernel version, which is why I removed that line. The more important change is that the docker apt repository is no longer at http://get.docker.io/ubuntu (should be https), BUT in order for a GCE node to get apt packages from a repo like that, apt-transport-https must be installed. I'll submit that pull request now.

**Comment by clalansingh** [comment]
My ansible-docker pull request has been merged now (https://github.com/AnsibleShipyard/ansible-docker/pull/1)

**Comment by kellrott** [comment]
Congratulations.

**Pull request merged**
